name: Promote Release

on:
    push:
        tags:
            - "v*"

permissions:
    id-token: write
    contents: read

jobs:
    promote:
        strategy:
            matrix:
                service: [catalog, cart, orders, checkout, ui]
        runs-on: ubuntu-latest
        steps:
            - uses: aws-actions/configure-aws-credentials@v6.2.4
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                  aws-region: ${{ secrets.AWS_REGION_ID }}
            - uses: aws-actions/amazon-ecr-login@v2
              id: ecr-login
            - name: Retag existing image with version
              run: |
                  REGISTRY=${{ steps.ecr-login.outputs.registry }}
                  VERSION=${GITHUB_REF_NAME}
                  docker buildx imagetools create \
                    -t $REGISTRY/retail-store/${{ matrix.service }}:$VERSION \
                    $REGISTRY/retail-store/${{ matrix.service }}:${{ github.sha }}
    update-chart:
        needs: promote
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
              with:
                  repository: yaboulhouda/retail-store-chart
                  token: ${{ secrets.CHART_REPO_PAT }}

            - name: Update image tags
              run: |
                  VERSION=${GITHUB_REF_NAME}
                  for service in catalog cart orders checkout ui; do
                      yq -i ".image.tag = \"$VERSION\"" charts/$service/values.yaml
                  done

            - name: Commit and push
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git add .
                  git commit -m "chore: promote images to $VERSION" || echo "Nothing to commit"
                  git push
